### ISSUE TITLE
Recurring payments docs & APIs endpoints missing

### ISSUE THREAD

**Issue by omerbaflah** [paytabscom/paytabs-php-laravel-package#13]
- How do I create recurring payments for customers for a specific period of time with monthly or yearly biases?

- Note :
There is an option to create Repeat Billing in the PayTabs dashboard menu but we need this as an APIs.

**Comment by omerbaflah** [comment]
CC: @Walaa-Elsaeed-93

**Comment by Walaa-Elsaeed-93** [comment]
you can find it in part 6 in the usage in the README file .

" if you want to pass the Tokenization option you can use

  ->sendTokinse(true)
if you want to make a payment via token you can use

  ->sendTransaction('transaction_type','recurring')
  ->sendToken('transRef returned to you in the same first payment page','token returned from the first payment page created with Tokenization option') "
