### ISSUE TITLE
error wen it try create payment page Undefined index:

### ISSUE THREAD

**Issue by Tayeb-Ali** [paytabscom/paytabs-php-laravel-package#2]
i try crate payPage but affter send request i get error **say**
`ErrorException (E_NOTICE)
Undefined index:`
[ScreenShot](https://ibb.co/cTb3WLC)
**from**
`…/vendor/paytabscom/laravel_paytabs/src/paytabs_core.php690`

`
    private function __construct($region, $profile_id, $server_key)
    {
        $this->base_url = self::BASE_URLS[$region]['endpoint'];
        $this->setAuth($profile_id, $server_key);
    }`

**my code to crate page:**

`
//use Paytabscom\Laravel_paytabs\paypage;
use Paytabscom\Laravel_paytabs\Facades\paypage;

  $pay= Paypage::sendPaymentCode('all')
            ->sendTransaction('sale')
            ->sendCart(10,1000,'test')
            ->sendCustomerDetails('Walaa Elsaeed', 'w.elsaeed@paytabs.com', '01092540925', 'test', 'Nasr City', 'Cairo', 'Egypt', '1234','100.279.20.10')
            ->sendShippingDetails('Walaa Elsaeed', 'w.elsaeed@paytabs.com', '01092540925', 'test', 'Nasr City', 'Cairo', 'Egypt', '1234','100.279.20.10')
            ->sendURLs($this->returnUrl, 'callback_url')
            ->sendLanguage('ar')
            ->create_pay_page();
        return $pay;`

**Comment by Walaa-Elsaeed-93** [comment]
@Tayeb-Ali  you must add your configuration in the config / paytabs.php file

**Comment by Walaa-Elsaeed-93** [comment]
@Tayeb-Ali you must add your merchant configuration in config/paytabs.php
