### ISSUE TITLE
When to support PHP8?

### ISSUE THREAD

**Issue by mohamedsabil83** [paytabscom/paytabs-php-laravel-package#4]
Hi, We developed a new market project with Laravel 8 and PHP8.
Any ETA for supporting PHP8 as we plan to use your service? Or, is it ready to work with PHP8?

**Comment by Walaa-Elsaeed-93** [comment]
Hi Mohamed, It's already supported.
you can check.

**Comment by mohamedsabil83** [comment]
I just make a PR [#6] to update **composer.json** to support PHP8
