### ISSUE TITLE
419 page expired in php  7.4

### ISSUE THREAD

**Issue by sehsah** [paytabscom/paytabs-php-laravel-package#9]
when redirect after pay 
show me error 419 page expired and user logout 
it's work fine in php 7.3 but from 7.4 to 8.1 not working

**Comment by atmonshi** [comment]
I am facing the same issue on laravel 9 with PHP 8.1
I guess the token is not sent back after the payment is done

**Comment by yoosinpaddy** [comment]
> when redirect after pay show me error 419 page expired and user logout it's work fine in php 7.3 but from 7.4 to 8.1 not working
> I am facing the same issue on laravel 9 with PHP 8.1 I guess the token is not sent back after the payment is done

As a temporary fix add the return and call back urls to VerifyCsrfToken.php, if the url have the same path say www.example.com/paytabs/xxxx 
Then you can add as follows

`protected $except = [
        'paytabs/*'
    ];`

Finally, do 
`php artisan optimize`
@atmonshi @sehsah

**Comment by aeq-dev** [comment]
Hi @yoosinpaddy 
I have the same issue and I set except paytabs as you suggested but it doesn't work !

**Comment by aeq-dev** [comment]
Oops never mind ! I should set paytabs and paytabs/*

**Comment by aeq-dev** [comment]
@sehsah 
In addition what @yoosinpaddy said, there's a simple solution to keep user logged in, just enable remember me on login page, or may you force users to login with remember me always yes.
I hope it helps you :)
